/* Regenerates src/styles/letters.css from src/data/wordmarks.json.
 *
 *   npm run letters
 *
 * Emits three things per letter, all of which come straight from the artwork
 * and none of which should be typed by hand:
 *
 *   --glyph       the mask stencil (see the header it writes into letters.css)
 *   flex-grow     the letter's intrinsic pixel width, which is what gives each
 *                 letter its share of the word's vw width
 *   aspect-ratio  intrinsic width / height — needed because blanking the bitmap
 *                 in the CSS throws the intrinsic size away
 *
 * The hand-tuned arc nudges (--i / --dx / --dy / --dr) stay in global.css, under
 * Tape slider. Those encode taste; everything here is measurement.
 *
 * This is the one stylesheet global.css does not absorb, precisely because it is
 * rewritten wholesale here; global.css @imports it, so the layout still pulls in
 * a single file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const marks = JSON.parse(readFileSync(join(ROOT, "src/data/wordmarks.json"), "utf8"));

/** PNG header: width and height are big-endian uint32 at bytes 16 and 20. */
function dims(webPath) {
  const b = readFileSync(join(ROOT, "public", webPath));
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

function block(selector, list) {
  return list
    .map((g, i) => {
      const d = dims(g.src);
      return (
        `\n/* ${g.letter} — ${d.w}x${d.h} */\n` +
        `${selector}:nth-child(${i + 1}) {\n` +
        `  --glyph: url("${g.src}");\n` +
        `  flex-grow: ${d.w};\n` +
        `  aspect-ratio: ${d.w} / ${d.h};\n` +
        `}\n`
      );
    })
    .join("");
}

const out = `/* ==========================================================================
   GENERATED by scripts/gen-letters.mjs — do not hand-edit.
   Run \`npm run letters\` after changing src/data/wordmarks.json or the artwork.

   Pulled in by global.css, which @imports it rather than absorbing it — this
   file is machine-written and that one is not.

   Letter stencils. The PNGs are flat #fcd805 with the shape entirely in their
   alpha, so each is used as a mask rather than shown: the element paints
   --word-colour and the stencil punches the letter out of it. That is what lets
   the letters take each tape's colour.

   Plain url() paths, not base64 data URIs. Masks are subject to same-origin,
   which a file:// page fails — the old static build had to inline all 39KB of
   artwork for that reason alone. Served over HTTP by Next, the paths just work,
   and the browser caches the PNGs like any other image.

   THE is permanent. CREATIVE's is a stopgap until the per-slide artwork lands:
   delete its block below plus the matching rule in global.css and only the
   recolour goes — the dip does not depend on it.
   ========================================================================== */

/* THE — the mask is also what animates; global.css slides mask-position. */
${block(".top-title img", marks.the)}
/* CREATIVE — the mask stays parked at 0 0 and travels with the image;
   .glyph does the clipping. */
${block(".bottom-title .glyph", marks.creative)}`;

writeFileSync(join(ROOT, "src/styles/letters.css"), out);
console.log(
  `wrote src/styles/letters.css — ${(out.length / 1024).toFixed(1)}KB, ` +
    `${marks.the.length + marks.creative.length} letters`
);
