/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tapes: Tape;
    news: News;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tapes: TapesSelect<false> | TapesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every swappable file on the site. Replacing one here replaces it everywhere it appears.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the picture says, for a reader who cannot see it. Leave the story's own alt empty to use this one.
   */
  alt: string;
  /**
   * Site furniture — a cursor, a texture, a 3D roll. Tick this and the file cannot be deleted until it is unticked.
   */
  protected?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The six rolls, in orbit order. Artwork is still referenced by path; the copy, colours and powers are live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tapes".
 */
export interface Tape {
  id: number;
  /**
   * Screen-reader name for the roll button.
   */
  label: string;
  /**
   * The route's last segment: /products/<slug>, and the artwork folder's name. Changing it breaks both.
   */
  slug: string;
  /**
   * Position on the orbit, low to high. The first one is selected on load.
   */
  order: number;
  /**
   * Which word the bottom title spells — a key of `words` in src/data/wordmarks.json, where its letterforms are. Not free text: the stencils are generated per word into letters.css and selected by this.
   */
  wordmark: string;
  /**
   * Thumbnail on the orbit, made from the card at 108px.
   */
  roll: number | Media;
  /**
   * Hang tag at the centre of the stage.
   */
  card: number | Media;
  /**
   * The inner page's key visual — the roll shot square-on. Optional: leave it empty and the page falls back to the card, which is a working page rather than a hole in one.
   */
  hero?: (number | null) | Media;
  /**
   * Exactly two. The layout places each by hand, so a third would have nowhere to go.
   */
  showcase: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * The siblings' printed labels, one per variant id. Optional and empty for every tape today — each card falls back to the card artwork above, so the row works rather than showing three broken images.
   */
  faces?:
    | {
        variant: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  model: string;
  /**
   * A second mesh for the inner page where the slider's is not right for it. Optional.
   */
  modelInner?: string | null;
  /**
   * How see-through the tape is, 0 to 1. A fact about the tape rather than a rendering setting, which is why it lives here.
   */
  clarity?: number | null;
  /**
   * Chips in the left column. Four is the ceiling — the tilt angles run out at five.
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Paragraph under the chips.
   */
  copy: string;
  /**
   * Exactly two lines, broken where the design breaks them rather than wherever the measure lands.
   */
  origin: {
    text: string;
    id?: string | null;
  }[];
  /**
   * One entry per line.
   */
  character: {
    text: string;
    id?: string | null;
  }[];
  reel: {
    /**
     * Broken by hand: where display type this size turns is a drawing decision, not something to infer from the string at render time.
     */
    headline: {
      text: string;
      id?: string | null;
    }[];
    note: {
      text: string;
      id?: string | null;
    }[];
    /**
     * Exactly four. The grid is drawn for four and a fifth has nowhere to go.
     */
    shots: {
      image: number | Media;
      id?: string | null;
    }[];
  };
  /**
   * Exactly three — the section is a stack of three cards. Per tape rather than per range: a masking tape and a cloth tape are not good at the same things.
   */
  powers: {
    /**
     * Stable key. Not shown on the page.
     */
    key: string;
    /**
     * First line of the claim.
     */
    titleTop: string;
    /**
     * Second line. Exactly two: the card is a fixed shape and a third would overflow it.
     */
    titleBottom: string;
    /**
     * One sentence, under the mark. Sentence case here — the caps on the page are the section's setting, so this stays readable in a screen reader.
     */
    copy: string;
    id?: string | null;
  }[];
  /**
   * Reaches the page as custom properties on the roll button; the animation reads them from there.
   */
  colours: {
    /**
     * Band behind the roll when selected.
     */
    ring: string;
    /**
     * Colour the stage floods with.
     */
    bg: string;
    /**
     * THE and the tape's own word.
     */
    word: string;
    /**
     * Chip fill.
     */
    tagBg: string;
    /**
     * Chip text. Check it against tagBg — 4.5:1 or better.
     */
    tagInk: string;
    /**
     * Body copy in the left column.
     */
    ink: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Stories and events. Exactly one story is featured; ticking a new one unticks the old.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Written exactly as it paints. The lead story is set in caps because it is display type; a card's title is sentence case because it is a sentence. Neither is text-transform doing it.
   */
  title: string;
  /**
   * The route's last segment: /news/<slug>. Changing it breaks any link already published to the old one.
   */
  slug: string;
  /**
   * The filter tab this sits under, and what the card wears at its top edge. The tabs are counted off these values — there is no second list to keep in step.
   */
  kind: 'event' | 'news';
  /**
   * Prints as the large day and the small month beneath it. Both are derived from this, so they cannot disagree.
   */
  date: string;
  /**
   * The story the newsroom leads on — an editorial choice, not the newest date. Ticking this unticks whichever story held it before.
   */
  featured?: boolean | null;
  /**
   * Converted to WebP on upload. The featured shot runs full-bleed off the top corner of the inner page, so it wants to be the largest of them.
   */
  image: number | Media;
  /**
   * Leave empty where the picture is decoration beside a title that already says it — the grid cards. The featured shot and the inner page carry a real one. Falls back to the alt set on the image itself.
   */
  alt?: string | null;
  /**
   * The heading at the head of the article's own sheet. Not a summary and not a standfirst — display type doing a heading's job, written in the case it paints.
   */
  deck: string;
  /**
   * One entry per paragraph. The read time is counted from these, so it comes right on its own as the writing grows.
   */
  body: {
    text: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tapes';
        value: number | Tape;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  protected?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tapes_select".
 */
export interface TapesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  order?: T;
  wordmark?: T;
  roll?: T;
  card?: T;
  hero?: T;
  showcase?:
    | T
    | {
        image?: T;
        id?: T;
      };
  faces?:
    | T
    | {
        variant?: T;
        image?: T;
        id?: T;
      };
  model?: T;
  modelInner?: T;
  clarity?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  copy?: T;
  origin?:
    | T
    | {
        text?: T;
        id?: T;
      };
  character?:
    | T
    | {
        text?: T;
        id?: T;
      };
  reel?:
    | T
    | {
        headline?:
          | T
          | {
              text?: T;
              id?: T;
            };
        note?:
          | T
          | {
              text?: T;
              id?: T;
            };
        shots?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  powers?:
    | T
    | {
        key?: T;
        titleTop?: T;
        titleBottom?: T;
        copy?: T;
        id?: T;
      };
  colours?:
    | T
    | {
        ring?: T;
        bg?: T;
        word?: T;
        tagBg?: T;
        tagInk?: T;
        ink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  date?: T;
  featured?: T;
  image?: T;
  alt?: T;
  deck?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}