/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tapes: Tape;
    news: News;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tapes: TapesSelect<false> | TapesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    about: About;
    menu: Menu;
    contact: Contact;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every swappable file on the site. Replacing one here replaces it everywhere it appears.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the picture says, for a reader who cannot see it. Leave the story's own alt empty to use this one.
   */
  alt: string;
  /**
   * Site furniture — a cursor, a texture, a 3D roll. Tick this and the file cannot be deleted until it is unticked.
   */
  protected?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * The products themselves — what each tape IS. The home page's orbit is a separate record (Globals → Homepage), so adding a tape here does not put it on the front page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tapes".
 */
export interface Tape {
  id: number;
  /**
   * The route's last segment: /products/<slug>, and the artwork folder's name. Changing it breaks both.
   */
  slug: string;
  /**
   * Position in the row at /products, low to high — and the order NEXT UP walks at the foot of a product page. NOT the home page's orbit, which is set on the Homepage global and ordered by dragging the rolls there.
   */
  order: number;
  /**
   * Screen-reader name for the roll button.
   */
  label: string;
  /**
   * Which word the bottom title spells — a key of `words` in src/data/wordmarks.json, where its letterforms are. Not free text: the stencils are generated per word into letters.css and selected by this.
   */
  wordmark: string;
  /**
   * The inner page's key visual — the roll shot square-on. Optional: leave it empty and the page falls back to the card, which is a working page rather than a hole in one.
   */
  hero?: (number | null) | Media;
  /**
   * The hang tag. Drawn on the row at /products, in THE RUN below, and used as this page's key visual whenever no hero shot is set.
   */
  card: number | Media;
  model: string;
  /**
   * Where this tape comes from — one paragraph. Type {{tape}} where the strip of tape should be stuck across it: it can go between any two words, or at the very end. Add settings inside the braces to lay it down differently — {{tape rotate=-8}} turns it, {{tape rotate=30 width=100 height=40}} turns and resizes it. rotate is in degrees, clockwise; width and height are in pixels at desktop size and both are optional. WHICH tape it is, is set in the code and is normally this product's own. Line breaks are just for reading; the paragraph flows to its own width on the page.
   */
  origin: string;
  /**
   * What it is like to use. One line per line.
   */
  character: string;
  /**
   * The photograph beside the origin story. ONE — it was two for a while, mirroring the home page's stage, and the second was never drawn on a product page.
   */
  showcase: number | Media;
  /**
   * One printed label per variant, in the order they should stand — the middle one is the raised card. Up to three, which is what the row is drawn for. Leave it empty and the section shows three of the hang tag, which is what every tape did before the artwork existed.
   */
  faces?:
    | {
        /**
         * The round printed label. Its own Alt text in the media library is what a screen reader is told, so put the variant's name there.
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Exactly three — the section is a stack of three cards. Per tape rather than per range: a masking tape and a cloth tape are not good at the same things.
   */
  powers: {
    key: string;
    /**
     * First line of the claim.
     */
    titleTop: string;
    /**
     * Second line. Exactly two: the card is a fixed shape and a third would overflow it.
     */
    titleBottom: string;
    /**
     * One sentence, under the mark. Sentence case here — the caps on the page are the section's setting, so this stays readable in a screen reader.
     */
    copy: string;
    /**
     * The drawing that drops onto the card. An SVG — and it may be an ANIMATED one: an export that carries its own motion keeps it, and the page only decides when it plays. A flat SVG is dropped on by the section's own bounce instead, so either kind works. Optional: leave it empty and the card wears the stock box.
     */
    mark?: (number | null) | Media;
    id?: string | null;
  }[];
  reel: {
    /**
     * The claim across the pinned frame. One line per line — press Enter where the design breaks it, because where display type this size turns is a drawing decision rather than something to infer from the measure.
     */
    headline: string;
    /**
     * The hand-written note beside the label. One line per line, same as above.
     */
    note: string;
    /**
     * Exactly four. The grid is drawn for four and a fifth has nowhere to go.
     */
    shots: {
      image: number | Media;
      id?: string | null;
    }[];
  };
  /**
   * The line under this product in a Google result, and nothing else — it is NOT drawn on the page. One sentence, about 150 characters; longer is cut off mid-word.
   */
  copy: string;
  /**
   * NOT SHOWN ON THIS PAGE any more. The chips beside the home page's stage are the slider's own now (Globals -> Homepage), and nothing on a product page draws these. Hidden rather than deleted so the words are not lost; say if they should go.
   */
  tags?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reaches the page as custom properties on the roll button; the animation reads them from there.
   */
  colours: {
    /**
     * Band behind the roll when it is the selected one.
     */
    ring: string;
    /**
     * The colour the stage floods with.
     */
    bg: string;
    /**
     * THE and the tape's own word.
     */
    word: string;
    /**
     * The chip behind the strapline.
     */
    tagBg: string;
    /**
     * Check it against the chip fill — 4.5:1 or better.
     */
    tagInk: string;
    /**
     * The line of copy in the left column.
     */
    ink: string;
  };
  sections?: {
    /**
     * The ground the roll stands on. Blank = the palette's Sheet.
     */
    introBg?: string | null;
    /**
     * THE and the tape's word, punched across the screen. Blank = the palette's Wordmark.
     */
    introWord?: string | null;
    /**
     * Blank = the palette's Chip fill.
     */
    introTagBg?: string | null;
    /**
     * Check it against the chip fill — 4.5:1 or better. Blank = the palette's Chip text.
     */
    introTagInk?: string | null;
    /**
     * Blank = the palette's Body copy.
     */
    introInk?: string | null;
    /**
     * Site default #0d470c.
     */
    originBg?: string | null;
    /**
     * The story, the rule under its last word, the arrow, and the note in the margin. ONE field, because in the design they are all one colour. Site default #b6fe00.
     */
    originInk?: string | null;
    /**
     * Site default #0d470c.
     */
    siblingsBg?: string | null;
    /**
     * The three grade cards themselves. Site default #c6fd00.
     */
    siblingsCard?: string | null;
    /**
     * Site default #a8f000.
     */
    siblingsInk?: string | null;
    /**
     * The ground the stack of cards passes over. Site default #b6fe00.
     */
    powersBg?: string | null;
    /**
     * The two words themselves, one either side of the stack. Set on the sheet rather than on a card, which is why it is its own colour and not the ink below. Site default #013900.
     */
    powersHeading?: string | null;
    /**
     * The card being read, once it has filled. Site default #0d470c.
     */
    powersCard?: string | null;
    /**
     * A card still waiting its turn. Close to the sheet on purpose: a resting card is meant to be sensed rather than found. Site default #9bdc00.
     */
    powersCardRest?: string | null;
    /**
     * The claim and the sentence. Site default #b6fe00.
     */
    powersInk?: string | null;
    /**
     * Site default #b6fe00.
     */
    reelBg?: string | null;
    /**
     * Site default #013900.
     */
    reelInk?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Stories and events. Exactly one story is featured; ticking a new one unticks the old.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Written exactly as it paints. The lead story is set in caps because it is display type; a card's title is sentence case because it is a sentence. Neither is text-transform doing it.
   */
  title: string;
  /**
   * The route's last segment: /news/<slug>. Changing it breaks any link already published to the old one.
   */
  slug: string;
  /**
   * The filter tab this sits under, and what the card wears at its top edge. The tabs are counted off these values — there is no second list to keep in step.
   */
  kind: 'event' | 'news';
  /**
   * Prints as the large day and the small month beneath it. Both are derived from this, so they cannot disagree.
   */
  date: string;
  /**
   * The story the newsroom leads on — an editorial choice, not the newest date. Ticking this unticks whichever story held it before.
   */
  featured?: boolean | null;
  /**
   * Converted to WebP on upload. The featured shot runs full-bleed off the top corner of the inner page, so it wants to be the largest of them.
   */
  image: number | Media;
  /**
   * Leave empty where the picture is decoration beside a title that already says it — the grid cards. The featured shot and the inner page carry a real one. Falls back to the alt set on the image itself.
   */
  alt?: string | null;
  /**
   * The heading at the head of the article's own sheet. Not a summary and not a standfirst — display type doing a heading's job, written in the case it paints.
   */
  deck: string;
  /**
   * One entry per paragraph. The read time is counted from these, so it comes right on its own as the writing grows.
   */
  body: {
    text: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tapes';
        value: number | Tape;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  protected?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tapes_select".
 */
export interface TapesSelect<T extends boolean = true> {
  slug?: T;
  order?: T;
  label?: T;
  wordmark?: T;
  hero?: T;
  card?: T;
  model?: T;
  origin?: T;
  character?: T;
  showcase?: T;
  faces?:
    | T
    | {
        image?: T;
        id?: T;
      };
  powers?:
    | T
    | {
        key?: T;
        titleTop?: T;
        titleBottom?: T;
        copy?: T;
        mark?: T;
        id?: T;
      };
  reel?:
    | T
    | {
        headline?: T;
        note?: T;
        shots?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  copy?: T;
  tags?:
    | T
    | {
        text?: T;
        id?: T;
      };
  colours?:
    | T
    | {
        ring?: T;
        bg?: T;
        word?: T;
        tagBg?: T;
        tagInk?: T;
        ink?: T;
      };
  sections?:
    | T
    | {
        introBg?: T;
        introWord?: T;
        introTagBg?: T;
        introTagInk?: T;
        introInk?: T;
        originBg?: T;
        originInk?: T;
        siblingsBg?: T;
        siblingsCard?: T;
        siblingsInk?: T;
        powersBg?: T;
        powersHeading?: T;
        powersCard?: T;
        powersCardRest?: T;
        powersInk?: T;
        reelBg?: T;
        reelInk?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  kind?: T;
  date?: T;
  featured?: T;
  image?: T;
  alt?: T;
  deck?: T;
  body?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The home page. The tape slider's rolls are set here, in the order they orbit — independently of the Tapes collection, which describes the products themselves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * The small line above the headline, on the two rows the design breaks it on. The brand mark drops into the gap between them, so exactly two.
   */
  heroKicker?: string | null;
  /**
   * Two centred rows. One line per row — the break is set by the design, not by wrapping.
   */
  heroHeadline?: string | null;
  /**
   * The two small rows in the corner.
   */
  heroCornerMark?: string | null;
  /**
   * The running line across the carton. This one WRAPS, so it is one paragraph rather than set rows.
   */
  heroCardboard?: string | null;
  /**
   * Capitals. The roll sits in the gap after this half.
   */
  bandHead?: string | null;
  bandTail?: string | null;
  slider: {
    /**
     * The line above the stage. Capitals — the page does not transform it, so what is typed is what is drawn.
     */
    subhead: string;
    /**
     * The orbit, in the order it turns. Drag to reorder; the first one is selected on load. Adding a roll here does not create a product, and removing one does not delete anything.
     */
    rolls: {
      /**
       * Stable id for this roll. Not shown to a reader — it identifies the slide to the engine and picks which tape the photographs are held down with (see strips.ts). Match the product's slug where there is one, so the right strip is chosen; anything unrecognised gets the masking strip.
       */
      key: string;
      /**
       * What the roll's button is called for somebody who cannot see it. The only text on this slide a screen reader announces.
       */
      label: string;
      /**
       * The roll on the orbit, drawn at 108px. Usually the card shot cropped square.
       */
      thumb: number | Media;
      /**
       * Hang tag at the centre of the stage.
       */
      card: number | Media;
      /**
       * Exactly two. The stage places each by hand, so a third would have nowhere to go.
       */
      showcase: {
        image: number | Media;
        id?: string | null;
      }[];
      /**
       * Path to the 3D roll under /public/assets/tapes. The slider PRELOADS these, so a wrong one breaks the home page rather than one product. Geometry rather than content, which is why it is a path and not an upload.
       */
      model: string;
      /**
       * Which word the bottom title spells. Its letterforms are generated per word into letters.css, so this is a fixed list rather than free text.
       */
      wordmark: 'creative' | 'trusty' | 'buddy' | 'fixer' | 'reliable' | 'silent';
      /**
       * Chips beside the stage. Four is the ceiling — the tilt angles run out at five.
       */
      tags?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      /**
       * The paragraph under the chips.
       */
      copy: string;
      /**
       * Reaches the page as custom properties on the roll button; the stage floods from them when this roll is picked.
       */
      colours: {
        /**
         * Band behind the roll when selected.
         */
        ring: string;
        /**
         * Colour the stage floods with.
         */
        bg: string;
        /**
         * THE and the tape's own word.
         */
        word: string;
        /**
         * Chip fill.
         */
        tagBg: string;
        /**
         * Chip text. Check it against tagBg — 4.5:1 or better.
         */
        tagInk: string;
        /**
         * Body copy beside the stage.
         */
        ink: string;
      };
      id?: string | null;
    }[];
  };
  /**
   * The chip above the block. Capitals.
   */
  reasonsSubhead?: string | null;
  /**
   * Three rows at the design width. One line per row.
   */
  reasonsHeading?: string | null;
  /**
   * Three, in the order they are held. Exactly three: each has its own arrangement of photographs drawn against it, and a fourth would have nothing to stand in.
   */
  reasonsPanels?:
    | {
        /**
         * The small word in front.
         */
        lead: string;
        /**
         * The noun, which the design colours and tilts on its own.
         */
        word: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Three rows. One line per row.
   */
  stickHeading?: string | null;
  /**
   * Sentence case — it is a caption, not a heading.
   */
  stickSub?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything /about says, section by section. The layout is drawn in code; the words and the belt's photographs are here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * The statement, set on an arc. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  headline?: string | null;
  /**
   * The line under it. Exactly two rows — the roll comes up through the gap between them. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  kicker?: string | null;
  /**
   * Written by pen as the screen arrives. Sentence case: this one is handwriting, not display type. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  note?: string | null;
  /**
   * Three rows, top to bottom. The middle one is the one that carries the mark, and where it stops is what leaves the mark alone in the window.
   */
  belt?:
    | {
        /**
         * Where the row is parked, in vw of its own left edge. Negative is left. This is also the pose the page rests on with no script.
         */
        from: number;
        /**
         * Where it has travelled to by the end of the section. The difference is the travel — re-tune both if you add or remove pills.
         */
        to: number;
        /**
         * Left to right. Drag to reorder; the row is printed three times over so it never runs out of belt.
         */
        items?:
          | {
              kind: 'photo' | 'claim' | 'note' | 'roll' | 'mark';
              /**
               * How long the pill is. The height never changes.
               */
              size?: ('sm' | 'med' | 'xl' | 'xxl') | null;
              /**
               * Left empty the pill is drawn as a plain shape, which is what the belt does until the photographs land.
               */
              image?: (number | null) | Media;
              /**
               * Full crops the picture to the stadium. Inset keeps the whole picture and leaves the pill's green showing at the sides.
               */
              fit?: ('full' | 'inset') | null;
              /**
               * What the photograph shows, for a reader who cannot see it. Leave empty if it says nothing the page does not.
               */
              alt?: string | null;
              /**
               * The number beside the heading — 01, 02, 03.
               */
              index?: string | null;
              /**
               * One line per row — the breaks are the drawing. A claim and a note take two; the roll's aside takes three.
               */
              lines?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The chip over the title. Capitals — the page does not transform it.
   */
  reasonKicker?: string | null;
  /**
   * Exactly two words: the line is set as two boxes. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  reasonTop?: string | null;
  /**
   * Exactly two words. The mark drops into the gap between them, so neither can carry both. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  reasonMiddle?: string | null;
  /**
   * One word, and it closes the sentence.
   */
  reasonBottom?: string | null;
  /**
   * Three rows — they are set inside a blob whose shape they have to fit. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  reasonMark?: string | null;
  /**
   * One row per line at desktop width. Two markers, both of which are part of the drawing: a pipe (|) is the hole the strip of tape lies in, and a slash (/) is where the phone turns the line. Neither is read out.
   */
  statement?: string | null;
  /**
   * Bent round the wave and crawled in from the right. One line — the curve is what breaks it.
   */
  wantedSentence?: string | null;
  /**
   * Four boxes at a fixed pitch. Their horizontal place is their place in this list; only the drop is set by hand.
   */
  wantedBoxes?:
    | {
        /**
         * Which of the four palettes this box is printed in. A fixed list and not free text: the colours are four rules in the stylesheet keyed on this, and a name with nothing behind it is a box with no colour.
         */
        key: 'clearer' | 'choose' | 'recognisable' | 'human';
        /**
         * Printed on the ceiling — 01.
         */
        num: string;
        /**
         * The drawing inside the box.
         */
        mark: 'strip' | 'parcel' | 'roll' | 'person';
        /**
         * How far down the screen the box sits, in vh. The scatter is the whole reason the four do not read as a row.
         */
        y: number;
        /**
         * The words across the floor of the box. One line per row — the breaks are the drawing, so what is typed is what is drawn.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sentence case — it runs into the headline.
   */
  ctaKicker?: string | null;
  /**
   * Three rows at the design width. One line per row — the breaks are the drawing, so what is typed is what is drawn.
   */
  ctaHeadline?: string | null;
  ctaLabel?: string | null;
  /**
   * A path on this site, or a full URL to leave it.
   */
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The pull-down menu, on every page. Rows hang in the order they are listed here — drag to reorder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  /**
   * Six is the ceiling: the panel drops to a measured height and the rows are sized to fill it, so a seventh would either overflow the paper or shrink the rest to fit a row only one page asked for.
   */
  items: {
    /**
     * What the row says. Capitals — the menu does not transform it, so what is typed is what is drawn, and it is what a screen reader announces.
     */
    label: string;
    /**
     * Where it goes. A path beginning with a slash for a page on this site; a full https:// address for somewhere else.
     */
    href: string;
    /**
     * The picture that shows behind the row on hover. Optional — a row without one falls back to the shared preview, which is what most of them have always used.
     */
    thumb?: (number | null) | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything /contact says. The layout is drawn in code; the words are here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * The chip above the title. Set in capitals — the page does not transform it, so what is typed is what is drawn.
   */
  kicker: string;
  /**
   * The page's h1, on the two lines the design breaks it on. Exactly two: each line is set on its own arc and a third has nowhere to go.
   */
  heading: {
    text: string;
    id?: string | null;
  }[];
  /**
   * The heading on the paper, over the form. Two lines, same as above.
   */
  sheetHeading: {
    text: string;
    id?: string | null;
  }[];
  /**
   * Exactly four, in the order they are read. The grid is drawn two-by-two and a fifth would have nowhere to sit.
   */
  fields: {
    /**
     * Which field this is. Picks the input's type and what the browser autofills into it — not shown to a reader.
     */
    key: 'name' | 'company' | 'phone' | 'email';
    /**
     * What it is called on the page, and what a screen reader announces. The design's second field was labelled NAME, the same as the first, which is almost certainly a placeholder — this is where that gets corrected.
     */
    label: string;
    id?: string | null;
  }[];
  /**
   * The big box under the four.
   */
  messageLabel: string;
  /**
   * The tall block down the right. Short — it is set vertically and a sentence would not fit.
   */
  sendLabel: string;
  email: {
    /**
     * As it is written on the note. Capitals, because that is how the note is drawn.
     */
    label: string;
    /**
     * What clicking it opens: mailto: and then the address, lower case. Separate from the line above because the note is drawn in capitals and a mailto: cannot carry them.
     */
    href: string;
  };
  phone: {
    /**
     * As it is read aloud, spaces and all.
     */
    label: string;
    /**
     * What a phone dials: tel: and then the number with no spaces in it. A tel: href cannot carry the spaces the number is read with, which is why this is its own box.
     */
    href: string;
  };
  /**
   * The strip holding the note to the board. Optional — without it the note is simply unpinned, which is a page rather than a hole in one.
   */
  tape?: (number | null) | Media;
  /**
   * The browser tab and the search result's blue line. Not shown on the page.
   */
  metaTitle: string;
  /**
   * The grey line under it in a search result. A sentence, about 150 characters — longer is cut off mid-word.
   */
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroKicker?: T;
  heroHeadline?: T;
  heroCornerMark?: T;
  heroCardboard?: T;
  bandHead?: T;
  bandTail?: T;
  slider?:
    | T
    | {
        subhead?: T;
        rolls?:
          | T
          | {
              key?: T;
              label?: T;
              thumb?: T;
              card?: T;
              showcase?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              model?: T;
              wordmark?: T;
              tags?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              copy?: T;
              colours?:
                | T
                | {
                    ring?: T;
                    bg?: T;
                    word?: T;
                    tagBg?: T;
                    tagInk?: T;
                    ink?: T;
                  };
              id?: T;
            };
      };
  reasonsSubhead?: T;
  reasonsHeading?: T;
  reasonsPanels?:
    | T
    | {
        lead?: T;
        word?: T;
        id?: T;
      };
  stickHeading?: T;
  stickSub?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headline?: T;
  kicker?: T;
  note?: T;
  belt?:
    | T
    | {
        from?: T;
        to?: T;
        items?:
          | T
          | {
              kind?: T;
              size?: T;
              image?: T;
              fit?: T;
              alt?: T;
              index?: T;
              lines?: T;
              id?: T;
            };
        id?: T;
      };
  reasonKicker?: T;
  reasonTop?: T;
  reasonMiddle?: T;
  reasonBottom?: T;
  reasonMark?: T;
  statement?: T;
  wantedSentence?: T;
  wantedBoxes?:
    | T
    | {
        key?: T;
        num?: T;
        mark?: T;
        y?: T;
        label?: T;
        id?: T;
      };
  ctaKicker?: T;
  ctaHeadline?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        thumb?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  kicker?: T;
  heading?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sheetHeading?:
    | T
    | {
        text?: T;
        id?: T;
      };
  fields?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  messageLabel?: T;
  sendLabel?: T;
  email?:
    | T
    | {
        label?: T;
        href?: T;
      };
  phone?:
    | T
    | {
        label?: T;
        href?: T;
      };
  tape?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}